{% set version = "0.9.3" %}

package:
  name: tesseract-robotics-planning
  version: {{ version }}

source:
  - git_url: https://github.com/tesseract-robotics/tesseract_planning.git
    git_rev: {{ version }}
    git_depth: 50
    folder: src

build:
  number: 0

outputs:
  - name: tesseract-robotics-command-language
    script: build_command_lang.sh # [unix]
    script: bld_command_lang.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - lcov # [linux]
      host:
        - eigen
        - console_bridge
        - boost-cpp
        - tesseract-robotics-common
      run:
        - eigen
        - console_bridge
        - boost-cpp
        - tesseract-robotics-common
    # test:
    #   commands:
    #     - test -f ${PREFIX}/include/tesseract_common/macros.h  # [unix]
    #     - test -f ${PREFIX}/lib/libtesseract_common.so  # [unix]
    #     - test -f ${PREFIX}/lib/cmake/tesseract_common/tesseract_common-config.cmake # [unix]
    #     - if not exist %LIBRARY_PREFIX%\include\tesseract_common\macros.h (exit 1)  # [win]
    #     - if not exist %LIBRARY_PREFIX%\lib\tesseract_common.lib (exit 1)  # [win]
    #     - if not exist %LIBRARY_PREFIX%\bin\tesseract_common.dll (exit 1)  # [win]
    #     - if not exist %LIBRARY_PREFIX%\lib\cmake\tesseract_common\tesseract_common-config.cmake (exit 1)  # [win]
  - name: tesseract-robotics-motion-planners
    script: build_motion_planners.sh # [unix]
    script: bld_motion_planners.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - lcov # [linux]
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - pkg-config
        - pcl
      host:
        - eigen
        - console_bridge
        - boost-cpp
        - tesseract-robotics-common
        - tesseract-robotics-environment
        - tesseract-robotics-command-language
        - ompl
        - descartes-light
        - trajopt
        - trajopt-ifopt
        - trajopt-sco
        - trajopt-sqp
      run:
        - eigen
        - console_bridge
        - boost-cpp
        - tesseract-robotics-common
        - tesseract-robotics-environment
        - tesseract-robotics-command-language
        - ompl
        - descartes-light
        - trajopt
        - trajopt-ifopt
        - trajopt-sco
        - trajopt-sqp
  - name: tesseract-robotics-time-parameterization
    script: build_time_param.sh # [unix]
    script: bld_time_param.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - lcov # [linux]
        - pkg-config
      host:
        - eigen
        - console_bridge
        - tesseract-robotics-common
        - tesseract-robotics-command-language
      run:
        - eigen
        - console_bridge
        - tesseract-robotics-common
        - tesseract-robotics-command-language
  
about:
  home: https://github.com/tesseract-robotics/tesseract_planning
  summary: Motion Planning Environment
  license: Apache-2.0 AND BSD-3-Clause AND BSD-2-Clause
  license_file: 
    - src/LICENSE
    - src/LICENSE.Apache-2.0
    - src/LICENSE.BSD-3-Clause
    - src/LICENSE.BSD-2-Clause

extra:
  recipe-maintainers:
    - johnwason